// <auto-generated />
using System;
using AiContentFactory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiContentFactory.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902161504_AddSceneAudioTiming")]
    partial class AddSceneAudioTiming
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiContentFactory.Domain.AssetReferences.AssetReference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Prompt")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContentProjectId", "Type");

                    b.ToTable("asset_references", (string)null);
                });

            modelBuilder.Entity("AiContentFactory.Domain.Assets.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Prompt")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("SceneId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContentProjectId");

                    b.HasIndex("SceneId");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("AiContentFactory.Domain.ContentProjects.ContentProject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AspectRatio")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CaptionPresetId")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Niche")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("StylePresetId")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("TargetDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("TemplateId")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Topic")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VoicePresetId")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("content_projects", (string)null);
                });

            modelBuilder.Entity("AiContentFactory.Domain.Costs.AiUsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContentProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedCostUsd")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("SceneId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContentProjectId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("ai_usage_records", (string)null);
                });

            modelBuilder.Entity("AiContentFactory.Domain.Costs.VideoGenerationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CreditsUsed")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SceneId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("VideoGenerationRecords");
                });

            modelBuilder.Entity("AiContentFactory.Domain.Generation.GenerationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("ActualCredits")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<double?>("AudioDurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ContentProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstimatedCredits")
                        .HasColumnType("integer");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ModelTier")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("SceneId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContentProjectId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ContentProjectId", "SceneId", "Kind");

                    b.ToTable("generation_attempts", (string)null);
                });

            modelBuilder.Entity("AiContentFactory.Domain.Qa.QaScore", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double>("AudioQuality")
                        .HasColumnType("double precision");

                    b.Property<double>("Consistency")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ContentProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("FactualAccuracy")
                        .HasColumnType("double precision");

                    b.Property<double>("Hook")
                        .HasColumnType("double precision");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Overall")
                        .HasColumnType("double precision");

                    b.Property<double>("Pacing")
                        .HasColumnType("double precision");

                    b.Property<double>("PlatformSuitability")
                        .HasColumnType("double precision");

                    b.Property<double>("Story")
                        .HasColumnType("double precision");

                    b.Property<double>("SubtitleQuality")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("VisualQuality")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ContentProjectId");

                    b.ToTable("qa_scores", (string)null);
                });

            modelBuilder.Entity("AiContentFactory.Domain.Scripts.Script", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CallToAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ContentProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Escalation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hook")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payoff")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContentProjectId")
                        .IsUnique();

                    b.ToTable("scripts", (string)null);
                });

            modelBuilder.Entity("AiContentFactory.Domain.Storyboards.Scene", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AiVideoPriority")
                        .HasColumnType("integer");

                    b.Property<string>("AllocationRationale")
                        .HasColumnType("text");

                    b.Property<string>("AudioTimingJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("CameraDirection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CaptionText")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("GenerationPrompt")
                        .HasColumnType("text");

                    b.Property<string>("ModelTier")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Narration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NegativePrompt")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.Property<int>("SceneNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("StoryboardId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VisualDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VisualStyle")
                        .HasColumnType("text");

                    b.Property<string>("VisualType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("StoryboardId", "SceneNumber")
                        .IsUnique();

                    b.ToTable("scenes", (string)null);
                });

            modelBuilder.Entity("AiContentFactory.Domain.Storyboards.Storyboard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContentProjectId")
                        .IsUnique();

                    b.ToTable("storyboards", (string)null);
                });

            modelBuilder.Entity("AiContentFactory.Domain.ContentProjects.ContentProject", b =>
                {
                    b.OwnsOne("AiContentFactory.Domain.ContentProjects.CaptionSettings", "Captions", b1 =>
                        {
                            b1.Property<Guid>("ContentProjectId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Animation")
                                .HasColumnType("integer");

                            b1.Property<bool>("Bold")
                                .HasColumnType("boolean");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("boolean");

                            b1.Property<string>("FontFamily")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("FontSizePt")
                                .HasColumnType("integer");

                            b1.Property<string>("HighlightColor")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("Karaoke")
                                .HasColumnType("boolean");

                            b1.Property<int>("MarginVerticalPx")
                                .HasColumnType("integer");

                            b1.Property<int>("MaxWordsPerCue")
                                .HasColumnType("integer");

                            b1.Property<string>("OutlineColor")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<double>("OutlineWidth")
                                .HasColumnType("double precision");

                            b1.Property<int>("Position")
                                .HasColumnType("integer");

                            b1.Property<string>("PrimaryColor")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<double>("ShadowDepth")
                                .HasColumnType("double precision");

                            b1.Property<bool>("Uppercase")
                                .HasColumnType("boolean");

                            b1.HasKey("ContentProjectId");

                            b1.ToTable("content_projects");

                            b1.ToJson("Captions");

                            b1.WithOwner()
                                .HasForeignKey("ContentProjectId");
                        });

                    b.OwnsOne("AiContentFactory.Domain.ContentProjects.ContentIdeaConfig", "IdeaConfig", b1 =>
                        {
                            b1.Property<Guid>("ContentProjectId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContentPillar")
                                .HasColumnType("text");

                            b1.Property<int>("CreditStrategy")
                                .HasColumnType("integer");

                            b1.Property<string>("Emotion")
                                .HasColumnType("text");

                            b1.Property<string>("HookStyle")
                                .HasColumnType("text");

                            b1.Property<string>("NarrationLanguage")
                                .HasColumnType("text");

                            b1.Property<double?>("SpeakingRate")
                                .HasColumnType("double precision");

                            b1.Property<string>("StoryType")
                                .HasColumnType("text");

                            b1.Property<string>("TargetAudience")
                                .HasColumnType("text");

                            b1.Property<int>("VoiceGender")
                                .HasColumnType("integer");

                            b1.Property<string>("VoiceStyle")
                                .HasColumnType("text");

                            b1.HasKey("ContentProjectId");

                            b1.ToTable("content_projects");

                            b1.ToJson("IdeaConfig");

                            b1.WithOwner()
                                .HasForeignKey("ContentProjectId");
                        });

                    b.OwnsOne("AiContentFactory.Domain.ContentProjects.GenerationProgress", "Progress", b1 =>
                        {
                            b1.Property<Guid>("ContentProjectId")
                                .HasColumnType("uuid");

                            b1.Property<int>("CompletedUnits")
                                .HasColumnType("integer");

                            b1.Property<string>("Message")
                                .HasColumnType("text");

                            b1.Property<string>("Stage")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("TotalUnits")
                                .HasColumnType("integer");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ContentProjectId");

                            b1.ToTable("content_projects");

                            b1.ToJson("Progress");

                            b1.WithOwner()
                                .HasForeignKey("ContentProjectId");
                        });

                    b.OwnsOne("AiContentFactory.Domain.ContentProjects.RenderValidationSummary", "LastRenderValidation", b1 =>
                        {
                            b1.Property<Guid>("ContentProjectId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CheckedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<double>("DurationSeconds")
                                .HasColumnType("double precision");

                            b1.Property<string>("ErrorsText")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("Ok")
                                .HasColumnType("boolean");

                            b1.Property<string>("Summary")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("WarningsText")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ContentProjectId");

                            b1.ToTable("content_projects");

                            b1.ToJson("LastRenderValidation");

                            b1.WithOwner()
                                .HasForeignKey("ContentProjectId");
                        });

                    b.Navigation("Captions")
                        .IsRequired();

                    b.Navigation("IdeaConfig")
                        .IsRequired();

                    b.Navigation("LastRenderValidation")
                        .IsRequired();

                    b.Navigation("Progress")
                        .IsRequired();
                });

            modelBuilder.Entity("AiContentFactory.Domain.Storyboards.Scene", b =>
                {
                    b.HasOne("AiContentFactory.Domain.Storyboards.Storyboard", null)
                        .WithMany("Scenes")
                        .HasForeignKey("StoryboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiContentFactory.Domain.Storyboards.Storyboard", b =>
                {
                    b.Navigation("Scenes");
                });
#pragma warning restore 612, 618
        }
    }
}
